//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
//

package carlanetpp.simulations.lightcontrol_v2;

import carlanet.CarlanetManager;
import carlanet.lightcontrol_v2.NodeMobility;
import inet.networklayer.configurator.ipv4.Ipv4NetworkConfigurator;
import inet.networklayer.ipv4.RoutingTableRecorder;
import simu5g.common.binder.Binder;
import simu5g.common.carrierAggregation.CarrierAggregation;
import simu5g.nodes.gNodeB;
import simu5g.nodes.NrUe;
import simu5g.world.radio.LteChannelControl;
import inet.node.contract.INetworkNode;

network Lightcontrol_v2
{
    parameters:
        @display("bgb=800,400;bgg=100,1,grey95");
        @figure[title](type=label; pos=0,-1; anchor=sw; color=darkblue; text="Car Light Control Network");

    submodules:

        carlanetManager: CarlanetManager {
            @display("p=50,275");
        }

        channelControl: LteChannelControl {
            @display("p=50,25;is=s");
        }
        routingRecorder: RoutingTableRecorder {
            @display("p=50,75;is=s");
        }
        configurator: Ipv4NetworkConfigurator {
            @display("p=50,125");
        }
        binder: Binder {
            @display("p=50,175;is=s");
        }
        carrierAggregation: CarrierAggregation {
            @display("p=50,225;is=s");
        }
        gnb: gNodeB {
            @display("p=100,225;is=vl");
        }

        VectorVehicle[1]: NodeMobility {
            @display("p=200,100");
        }

        carlaNodelightController: NrUe {
            @display("p=450,325");
        }

}